### ISSUE TITLE
Capturing Villagers

### ISSUE THREAD

**Issue by Rayqua2b** [Matyrobbrt/MobCapturingTool#1]
Can't capture vilagers without using dispenser. And when using dispenser on a villager while he's sleeping then placing him makes it dissappear.

Using Fabric 1.18.2 version of the mod with no other mods altering or modifying villager behaviour.

**Comment by Matyrobbrt** [comment]
Have you tried shift clicking the villager?

**Comment by Rayqua2b** [comment]
Yes I have, but it doesn't work

**Comment by Matyrobbrt** [comment]
Hmm okay, I am getting this fixed. One thing to note though: the villager **does not** despawn, it will teleport to the bed it was sleeping in due to the presence of the SleepingX, SleepingZ and SleepingY tags.

**Comment by Rayqua2b** [comment]
Oh ok, thank you then ^^
